const listInterest = [
  { value: "Football", label: "Football" },
  { value: "ReadBook", label: "Read Book" },
  { value: "Swimming", label: "Swimming" },
  { value: "Cooking", label: "Cooking" },
  { value: "Gaming", label: "Gaming" },
  { value: "Photography", label: "Photography" },
  { value: "Traveling", label: "Traveling" },
  { value: "Music", label: "Music" },
  { value: "Drawing", label: "Drawing" },
  { value: "Dancing", label: "Dancing" },
  { value: "Cycling", label: "Cycling" },
  { value: "Running", label: "Running" },
  { value: "Hiking", label: "Hiking" },
  { value: "Fishing", label: "Fishing" },
  { value: "Camping", label: "Camping" },
  { value: "Skiing", label: "Skiing" },
  { value: "Surfing", label: "Surfing" },
  { value: "Skateboarding", label: "Skateboarding" },
  { value: "MartialArts", label: "Martial Arts" },
  { value: "Yoga", label: "Yoga" },
  { value: "Meditation", label: "Meditation" },
  { value: "Acting", label: "Acting" },
  { value: "Singing", label: "Singing" },
  { value: "Baking", label: "Baking" },
  { value: "Painting", label: "Painting" },
  { value: "Writing", label: "Writing" },
  { value: "Chess", label: "Chess" },
  { value: "BoardGames", label: "Board Games" },
  { value: "PuzzleSolving", label: "Puzzle Solving" },
  { value: "Archery", label: "Archery" },
  { value: "HorseRiding", label: "Horse Riding" },
  { value: "ScubaDiving", label: "Scuba Diving" },
  { value: "Astronomy", label: "Astronomy" },
  { value: "BirdWatching", label: "Bird Watching" },
  { value: "Gardening", label: "Gardening" },
  { value: "Calligraphy", label: "Calligraphy" },
  { value: "Origami", label: "Origami" },
  { value: "Handicrafts", label: "Handicrafts" },
  { value: "Knitting", label: "Knitting" },
  { value: "Sewing", label: "Sewing" },
  { value: "Woodworking", label: "Woodworking" },
  { value: "DIYProjects", label: "DIY Projects" },
  { value: "CollectingStamps", label: "Collecting Stamps" },
  { value: "CollectingCoins", label: "Collecting Coins" },
  { value: "Origami", label: "Origami" },
  { value: "MagicTricks", label: "Magic Tricks" },
  { value: "Robotics", label: "Robotics" },
  { value: "Programming", label: "Programming" },
  { value: "RCVehicles", label: "RC Vehicles" },
  { value: "DroneFlying", label: "Drone Flying" },
  { value: "ModelBuilding", label: "Model Building" },
  { value: "Cosplaying", label: "Cosplaying" },
  { value: "Anime", label: "Anime" },
  { value: "KPop", label: "K-Pop" },
  { value: "FashionDesign", label: "Fashion Design" },
  { value: "Makeup", label: "Makeup" },
  { value: "HairStyling", label: "Hair Styling" },
  { value: "TattooDesign", label: "Tattoo Design" },
  { value: "Volunteering", label: "Volunteering" },
  { value: "PetCare", label: "Pet Care" },
  { value: "HorseRiding", label: "Horse Riding" },
  { value: "InteriorDesign", label: "Interior Design" },
  { value: "HomeDecor", label: "Home Decor" },
  { value: "WineTasting", label: "Wine Tasting" },
  { value: "CoffeeBrewing", label: "Coffee Brewing" },
  { value: "TeaTasting", label: "Tea Tasting" },
  { value: "StandUpComedy", label: "Stand-up Comedy" },
  { value: "Podcasting", label: "Podcasting" },
  { value: "PublicSpeaking", label: "Public Speaking" },
  { value: "Debating", label: "Debating" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Investing", label: "Investing" },
  { value: "StockTrading", label: "Stock Trading" },
  { value: "RealEstate", label: "Real Estate" },
  { value: "CarRacing", label: "Car Racing" },
  { value: "MotorcycleRiding", label: "Motorcycle Riding" },
  { value: "Sailing", label: "Sailing" },
  { value: "Paragliding", label: "Paragliding" },
  { value: "SkyDiving", label: "Sky Diving" },
  { value: "BungeeJumping", label: "Bungee Jumping" },
  { value: "Parkour", label: "Parkour" },
  { value: "Weightlifting", label: "Weightlifting" },
  { value: "Crossfit", label: "Crossfit" },
  { value: "Boxing", label: "Boxing" },
  { value: "Wrestling", label: "Wrestling" },
  { value: "Judo", label: "Judo" },
  { value: "Taekwondo", label: "Taekwondo" },
  { value: "Karate", label: "Karate" },
  { value: "MuayThai", label: "Muay Thai" },
  { value: "MixedMartialArts", label: "Mixed Martial Arts" },
  { value: "SelfDefense", label: "Self Defense" },
  { value: "SurvivalSkills", label: "Survival Skills" },
  { value: "Bushcraft", label: "Bushcraft" },
  { value: "Foraging", label: "Foraging" },
  { value: "Farming", label: "Farming" },
  { value: "Beekeeping", label: "Beekeeping" },
  { value: "Astrophotography", label: "Astrophotography" },
  { value: "Videography", label: "Videography" },
  { value: "Cinematography", label: "Cinematography" },
];

export default listInterest;
