const interests = [
  "Reading",
  "Writing",
  "Painting",
  "Drawing",
  "Singing",
  "Dancing",
  "Cooking",
  "Baking",
  "Photography",
  "Traveling",
  "Hiking",
  "Camping",
  "Fishing",
  "Cycling",
  "Running",
  "Swimming",
  "Surfing",
  "Skateboarding",
  "Snowboarding",
  "Skiing",
  "Chess",
  "Gaming",
  "Puzzles",
  "Board Games",
  "Card Games",
  "Magic Tricks",
  "Calligraphy",
  "Origami",
  "Gardening",
  "Woodworking",
  "Pottery",
  "Knitting",
  "Sewing",
  "Embroidery",
  "DIY Projects",
  "Scrapbooking",
  "Journaling",
  "Blogging",
  "Podcasting",
  "Vlogging",
  "Acting",
  "Stand-up Comedy",
  "Theater",
  "Musical Instruments",
  "Guitar",
  "Piano",
  "Drums",
  "Violin",
  "Saxophone",
  "DJing",
  "Robotics",
  "Coding",
  "Web Development",
  "App Development",
  "Graphic Design",
  "3D Modeling",
  "Animation",
  "Photography Editing",
  "Video Editing",
  "Filmmaking",
  "Astronomy",
  "Birdwatching",
  "Collecting Coins",
  "Collecting Stamps",
  "Antiquing",
  "Fossil Hunting",
  "Genealogy",
  "Investing",
  "Stock Trading",
  "Cryptocurrency",
  "Meditation",
  "Yoga",
  "Weightlifting",
  "Bodybuilding",
  "Martial Arts",
  "Boxing",
  "Wrestling",
  "Parkour",
  "Archery",
  "Shooting",
  "Horseback Riding",
  "Scuba Diving",
  "Skydiving",
  "Paragliding",
  "Rock Climbing",
  "Bungee Jumping",
  "Car Racing",
  "Motorcycling",
  "Drone Flying",
  "RC Cars",
  "Fashion Designing",
  "Makeup Artistry",
  "Tattoo Art",
  "Cosplay",
  "Anime",
  "K-pop",
  "K-dramas",
  "Board Game Design",
  "Escape Rooms",
  "Virtual Reality Gaming",
];

export default interests;
